
// Ringbuf Related CSR Address, range from 0x00000000 to 0x000003FF
typedef 'h0000 CSR_ADDR_BLOCK_START_ADDR_FOR_RINGBUFS;
typedef 'h0100 CSR_ADDR_BLOCK_SIZE_FOR_RINGBUFS;

typedef 'h0000 CSR_ADDR_BLOCK_START_ADDR_FOR_QP;
typedef 'h0010 CSR_ADDR_BLOCK_SIZE_FOR_EACH_QP;

    typedef 'h0000 CSR_ADDR_OFFSET_WQE_RINGBUF_BASE_ADDR_LOW;
    typedef 'h0001 CSR_ADDR_OFFSET_WQE_RINGBUF_BASE_ADDR_HIGH;
    typedef 'h0002 CSR_ADDR_OFFSET_WQE_RINGBUF_HEAD;
    typedef 'h0003 CSR_ADDR_OFFSET_WQE_RINGBUF_TAIL;

    typedef 'h0004 CSR_ADDR_OFFSET_RECV_RINGBUF_BASE_ADDR_LOW;
    typedef 'h0005 CSR_ADDR_OFFSET_RECV_RINGBUF_BASE_ADDR_HIGH;
    typedef 'h0006 CSR_ADDR_OFFSET_RECV_RINGBUF_HEAD;
    typedef 'h0007 CSR_ADDR_OFFSET_RECV_RINGBUF_TAIL;


typedef 'h0040 CSR_ADDR_BLOCK_START_ADDR_FOR_CMDQ;
    typedef 'h0000 CSR_ADDR_OFFSET_CMD_REQ_Q_RINGBUF_BASE_ADDR_LOW;
    typedef 'h0001 CSR_ADDR_OFFSET_CMD_REQ_Q_RINGBUF_BASE_ADDR_HIGH;
    typedef 'h0002 CSR_ADDR_OFFSET_CMD_REQ_Q_RINGBUF_HEAD;
    typedef 'h0003 CSR_ADDR_OFFSET_CMD_REQ_Q_RINGBUF_TAIL;

    typedef 'h0004 CSR_ADDR_OFFSET_CMD_RESP_Q_RINGBUF_BASE_ADDR_LOW;
    typedef 'h0005 CSR_ADDR_OFFSET_CMD_RESP_Q_RINGBUF_BASE_ADDR_HIGH;
    typedef 'h0006 CSR_ADDR_OFFSET_CMD_RESP_Q_RINGBUF_HEAD;
    typedef 'h0007 CSR_ADDR_OFFSET_CMD_RESP_Q_RINGBUF_TAIL;


typedef 'h0050 CSR_ADDR_BLOCK_START_ADDR_FOR_SIMPLE_NIC;
    typedef 'h0000 CSR_ADDR_OFFSET_SIMPLE_NIC_TX_Q_RINGBUF_BASE_ADDR_LOW;
    typedef 'h0001 CSR_ADDR_OFFSET_SIMPLE_NIC_TX_Q_RINGBUF_BASE_ADDR_HIGH;
    typedef 'h0002 CSR_ADDR_OFFSET_SIMPLE_NIC_TX_Q_RINGBUF_HEAD;
    typedef 'h0003 CSR_ADDR_OFFSET_SIMPLE_NIC_TX_Q_RINGBUF_TAIL;

    typedef 'h0004 CSR_ADDR_OFFSET_SIMPLE_NIC_RX_Q_RINGBUF_BASE_ADDR_LOW;
    typedef 'h0005 CSR_ADDR_OFFSET_SIMPLE_NIC_RX_Q_RINGBUF_BASE_ADDR_HIGH;
    typedef 'h0006 CSR_ADDR_OFFSET_SIMPLE_NIC_RX_Q_RINGBUF_HEAD;
    typedef 'h0007 CSR_ADDR_OFFSET_SIMPLE_NIC_RX_Q_RINGBUF_TAIL;


// Metrics Counter Related CSR Address, range from 0x00000400

typedef 'h3F00 CSR_ADDR_ROUTING_MASK_FOR_METRICS_OF_QPMRPGTQPC;
typedef 'h0100 CSR_ADDR_ROUTING_FOR_METRICS_RQ0;
typedef 'h0200 CSR_ADDR_ROUTING_FOR_METRICS_RQ1;
typedef 'h0300 CSR_ADDR_ROUTING_FOR_METRICS_RQ2;
typedef 'h0400 CSR_ADDR_ROUTING_FOR_METRICS_RQ3;

typedef 'h0500 CSR_ADDR_ROUTING_FOR_METRICS_PACKET_GEN_0;
typedef 'h0600 CSR_ADDR_ROUTING_FOR_METRICS_PACKET_GEN_1;
typedef 'h0700 CSR_ADDR_ROUTING_FOR_METRICS_PACKET_GEN_2;
typedef 'h0800 CSR_ADDR_ROUTING_FOR_METRICS_PACKET_GEN_3;


    typedef 'h0060 CSR_ADDR_ROUTING_MASK_FOR_METRICS_OF_SINGLE_RQ;
    typedef 'h0020 CSR_ADDR_ROUTING_FOR_METRICS_OF_ETHERNET_FRAME_IO_RECV;
        typedef 'h001F CSR_ADDR_LEAF_MASK_FOR_METRICS_ETHERNET_FRAME_IO_RECV;
        typedef 'h0000 CSR_ADDR_OFFSET_METRICS_ETHERNET_FRAME_IO_DISCARD_PACKET_CNT;
        typedef 'h0001 CSR_ADDR_OFFSET_METRICS_ETHERNET_FRAME_IO_SIMPLE_NIC_PACKET_CNT;
        typedef 'h0002 CSR_ADDR_OFFSET_METRICS_ETHERNET_FRAME_IO_RDMA_PACKET_CNT;
        typedef 'h0003 CSR_ADDR_OFFSET_METRICS_ETHERNET_FRAME_IO_NOT_READY_PACKET_CNT;
    
    typedef 'h0040 CSR_ADDR_ROUTING_FOR_METRICS_OF_ETHERNET_FRAME_IO_SEND;
        typedef 'h001F CSR_ADDR_LEAF_MASK_FOR_METRICS_ETHERNET_FRAME_IO_SEND;
        typedef 'h0000 CSR_ADDR_OFFSET_METRICS_ETHERNET_FRAME_IO_SEND_FIRST_BEAT_CNT;
        typedef 'h0001 CSR_ADDR_OFFSET_METRICS_ETHERNET_FRAME_IO_SEND_SECOND_BEAT_CNT;
        typedef 'h0002 CSR_ADDR_OFFSET_METRICS_ETHERNET_FRAME_IO_SEND_THIRD_BEAT_CNT;
        typedef 'h0003 CSR_ADDR_OFFSET_METRICS_ETHERNET_FRAME_IO_SEND_MORE_BEAT_CNT;

    typedef 'h001F CSR_ADDR_LEAF_MASK_FOR_METRICS_RQ_PACKET_VERIFY;
    typedef 'h0000 CSR_ADDR_OFFSET_METRICS_RQ_PACKET_VERIFY_INV_QP_ACCESS_FLAG_CNT;
    typedef 'h0001 CSR_ADDR_OFFSET_METRICS_RQ_PACKET_VERIFY_INV_OPCODE_CNT;
    typedef 'h0002 CSR_ADDR_OFFSET_METRICS_RQ_PACKET_VERIFY_INV_MR_KEY_CNT;
    typedef 'h0003 CSR_ADDR_OFFSET_METRICS_RQ_PACKET_VERIFY_MEM_OOB_CNT;
    typedef 'h0004 CSR_ADDR_OFFSET_METRICS_RQ_PACKET_VERIFY_INV_MR_ACCESS_FLAG_CNT;
    typedef 'h0005 CSR_ADDR_OFFSET_METRICS_RQ_PACKET_VERIFY_INV_HEADER_CNT;
    typedef 'h0006 CSR_ADDR_OFFSET_METRICS_RQ_PACKET_VERIFY_INV_QP_CTX_CNT;
    typedef 'h0007 CSR_ADDR_OFFSET_METRICS_RQ_PACKET_VERIFY_PKT_LEN_ERR_CNT;
    typedef 'h0008 CSR_ADDR_OFFSET_METRICS_RQ_PACKET_VERIFY_UNKNOWN_ERR_CNT;
    typedef 'h0009 CSR_ADDR_OFFSET_METRICS_RQ_DEBUG_COUNTER_1;

        