import math

CSR_ADDR_SEND_QUEUE_ADDR_LOW = 0x00 << 2
CSR_ADDR_SEND_QUEUE_ADDR_HIGH = 0x01 << 2
CSR_ADDR_SEND_QUEUE_HEAD = 0x02 << 2
CSR_ADDR_SEND_QUEUE_TAIL = 0x03 << 2

CSR_ADDR_META_REPORT_QUEUE_ADDR_LOW = 0x04 << 2
CSR_ADDR_META_REPORT_QUEUE_ADDR_HIGH = 0x05 << 2
CSR_ADDR_META_REPORT_QUEUE_HEAD = 0x06 << 2
CSR_ADDR_META_REPORT_QUEUE_TAIL = 0x07 << 2

CSR_ADDR_CMD_REQ_QUEUE_ADDR_LOW = 0x40 << 2
CSR_ADDR_CMD_REQ_QUEUE_ADDR_HIGH = 0x41 << 2
CSR_ADDR_CMD_REQ_QUEUE_HEAD = 0x42 << 2
CSR_ADDR_CMD_REQ_QUEUE_TAIL = 0x43 << 2

CSR_ADDR_CMD_RESP_QUEUE_ADDR_LOW = 0x44 << 2
CSR_ADDR_CMD_RESP_QUEUE_ADDR_HIGH = 0x45 << 2
CSR_ADDR_CMD_RESP_QUEUE_HEAD = 0x46 << 2
CSR_ADDR_CMD_RESP_QUEUE_TAIL = 0x47 << 2


CSR_ADDR_SIMPLE_NIX_TX_QUEUE_ADDR_LOW = 0x50 << 2
CSR_ADDR_SIMPLE_NIX_TX_QUEUE_ADDR_HIGH = 0x51 << 2
CSR_ADDR_SIMPLE_NIX_TX_QUEUE_HEAD = 0x52 << 2
CSR_ADDR_SIMPLE_NIX_TX_QUEUE_TAIL = 0x53 << 2

CSR_ADDR_SIMPLE_NIX_RX_QUEUE_ADDR_LOW = 0x54 << 2
CSR_ADDR_SIMPLE_NIX_RX_QUEUE_ADDR_HIGH = 0x55 << 2
CSR_ADDR_SIMPLE_NIX_RX_QUEUE_HEAD = 0x56 << 2
CSR_ADDR_SIMPLE_NIX_RX_QUEUE_TAIL = 0x57 << 2


MEM_REGION_PAGE_SIZE = 2 * 1024 * 1024  # 2MB


MAX_MR_CNT = 8192
LR_KEY_IDX_PART_WIDTH = int(math.log(MAX_MR_CNT, 2))
LR_KEY_KEY_PART_WIDTH = 8


MAX_QP_CNT = 1024
QPN_IDX_PART_WIDTH = int(math.log(MAX_QP_CNT, 2))
QPN_KEY_PART_WIDTH = 8
